# docker-compose -f ./example-docker-compose.yaml up
version: '2.2'
x-net:
  &net
  networks:
    - main
services:
  fakeservices.datajoint.io:
    <<: *net
    image: datajoint/nginx:v0.2.5
    environment:
      ## Supply configs in the convention ADD_{service}_{config}
      ## Example database
      - ADD_db_ENDPOINT=db:3306
      - ADD_db_TYPE=DATABASE
      ## Example upgrade HTTP -> HTTPS
      - HTTPS_PASSTHRU=TRUE
    volumes:
      ## needed only if specifying a custom domain with encryption
      - ./nginx/privkey.pem:/etc/letsencrypt/live/fakeservices.datajoint.io/privkey.pem:ro
      - ./nginx/fullchain.pem:/etc/letsencrypt/live/fakeservices.datajoint.io/fullchain.pem:ro
    ports:
      ## Expose ports to allow unencrypted and encrypted access
      - "80:80"
      - "443:443"
      - "3306:3306"
  db:
    <<: *net
    image: datajoint/mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=simple
    # ports:
    #   - "3306:3306"
    ## To persist MySQL data
    # volumes:
    #   - ./mysql/data:/var/lib/mysql
    #   - ./mysql/my.cnf:/etc/mysql/my.cnf
networks:
  main:
